In [5]:
# Toolkit for NLP processing 
import nltk
from nltk.tokenize import word_tokenize 
from nltk.corpus import stopwords
from  nltk.stem import WordNetLemmatizer
# Library for Natural Language Processing (Tokenize, Lemmatize, POS tagging, NER (name entitity recognition, Dependency Parsing)
import spacy 
import re 
# Library for data manipulation - i.e Dataframe looks like a table/spreadsheet (loads cs,json,sql into structure format)
import pandas as pd 
# module within matplotlib that provides a simple interface for creating charts
import matplotlib.pyplot as plt

<b><h3>Load Data</h3></b>

In [9]:
# import data from csv file
bbc_data = pd.read_csv("bbc_news .csv")

In [11]:
# printout the first five rows of the table
bbc_data.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [13]:
# get the details of the data
bbc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   object
 3   pubDate      1000 non-null   object
 4   guid         1000 non-null   object
 5   link         1000 non-null   object
 6   description  1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [17]:
# retrive first five rows of the title column
titles = pd.DataFrame(bbc_data['title'])
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

<b><h3>Clean Data</h3></b>

In [20]:
#convert the titles to lowercase 
titles['lowercase'] = titles['title'].str.lower()
titles.head()

,title,lowercase
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [24]:
# Remove stopword - using a predefined list of english word using lambda function 
# Loads a list of common English stop words (e.g., "the", "is", "and", "a", "in") from NLTK's corpus.
en_stopwords = stopwords.words('english')
# Split words from titles['lowercase'] remove stopwords and join it back as a single string
titles['no_stopwords'] = titles['lowercase'].apply(lambda x: ' ' .join([word for word in x.split() if word not in(en_stopwords)]))

In [26]:
# Remove punctuations 
titles['no_stopwords_no_punct'] = titles.apply(lambda x: re.sub(r"([^\w\s])","",x['no_stopwords']), axis=1)

In [34]:
# Tokenize 
titles['tokens_raw']= titles.apply(lambda x: word_tokenize(x['title']), axis=1)
titles['tokens_clean']= titles.apply(lambda x: word_tokenize(x['no_stopwords_no_punct']), axis=1)

In [37]:
# Lemmatize 
# 1. Create a lemmatize object using wordnet 
lemmatizer = WordNetLemmatizer()
titles['tokens_clean_lemmatized']= titles["tokens_clean"].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punct,token_raw,token_clean,tokens_raw,tokens_clean,tokens_clean_lemmatized
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]","[Can, I, refuse, to, work, ?]","[refuse, work]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic...","['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com...","[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga...","[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, years, queen, 70, seco...","[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]"

In [39]:
# It flattens a list of lists into a single flat list - e.g multiple arrays into a single big array
tokens_raw_list=sum(titles['tokens_raw'], [])
tokens_clean_list=sum(titles['tokens_clean_lemmatized'],[])

<b><h3>Post Tagging - Part of Speech Tagging</h3></b>

In [40]:
# create a variable and asssign it the english language model
nlp = spacy.load('en_core_web_sm')

In [45]:
# create spacy document to store the text in the right format - i.e as a single string with spaces between words
# using spacy language model - model runs over the text and analyse it linguistically and stors it in spacy document object
# nlp_doc hold the docs with detailed anotation - i.e each word part of speech tag
spacy_doc = nlp(' '.join(tokens_raw_list))

In [47]:
# store the result of part of speech tagging - creating a new DataFrame
pos_df = pd.DataFrame(columns=['token','pos_tag'])
# add rows to the created dataframe
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token':token.text, 'pos_tag':token.pos_ }])], ignore_index=True)

In [54]:
# count how many times a word appear and what part of speech it belongs to - create token frequency count
pos_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)
pos_df_counts.head(10)

     token pos_tag  counts
95       :   PUNCT     543
8        '   PUNCT     300
2897    in     ADP     187
4082    to    PART     175
3268    of     ADP     172
22       -   PUNCT     166
4043   the     DET     163
1856   and   CCONJ     147
15      's    PART     143
97       ?   PUNCT     130

In [57]:
# retrieve the most common nouns in our dataset
nouns = pos_df_counts[pos_df_counts.pos_tag == 'NOUN'][0:10]
nouns

       token pos_tag  counts
4267     war    NOUN      35
3552  record    NOUN      15
3416  police    NOUN      14
4356    year    NOUN      14
4316     win    NOUN      14
3061  living    NOUN      13
4009     tax    NOUN      13
2326     day    NOUN      12
3368  people    NOUN      12
2031    boss    NOUN      11

In [58]:
# retrieve the most common verbs in our dataset
verbs = pos_df_counts[pos_df_counts.pos_tag == 'VERB'][0:10]
verbs

       token pos_tag  counts
3687    says    VERB      30
9          '    VERB      14
2670   found    VERB      13
4317     win    VERB      12
4324    wins    VERB      10
2713     get    VERB       9
2388    dies    VERB       9
3990    take    VERB       8
2982  killed    VERB       8
3686     say    VERB       8

In [59]:
# retrieve the most common ADJECTIVES in our dataset
adj = pos_df_counts[pos_df_counts.pos_tag == 'ADJ'][0:10]
adj

        token pos_tag  counts
3244      new     ADJ      28
1400  Russian     ADJ      21
2606    final     ADJ      16
19          -     ADJ      14
2625    first     ADJ      12
3199     more     ADJ      10
1994      big     ADJ       9
2835     high     ADJ       9
3000     last     ADJ       8
3304    other     ADJ       8

<b><h3> NER - Named Entity Recognition</h3></b>

In [81]:
# create a new dataframe which would hold each token and its associated NER tagging
ner_df = pd.DataFrame(columns=['token','ner_tag'])
# add rows to the created dataframe
for token in spacy_doc.ents:
    ner_df = pd.concat([ner_df, pd.DataFrame.from_records([{'token':token.text, 'ner_tag':token.label_ }])], ignore_index=True)

In [82]:
ner_df.head()

         token   ner_tag
0    Liz Truss    PERSON
1           UK       GPE
2    Rationing   PRODUCT
3  superyachts  CARDINAL
4      Russian      NORP

In [83]:
# count how many times an entity appear  - create token frequency count
ner_df_counts = ner_df.groupby(['token', 'ner_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)
ner_df_counts.head(10)

               token      ner_tag  counts
965          Ukraine          GPE      47
955               UK          GPE      36
329          England          GPE      32
819          Russian         NORP      20
957               US          GPE      19
1031  World Cup 2022        EVENT      18
1058           first      ORDINAL      13
918       The Papers  WORK_OF_ART      13
378           France          GPE      12
226            China          GPE      11